### ISSUE TITLE
Rumble/Lightbar lingers

### ISSUE THREAD

**Issue by stramner** [Ryochan7/DS4Windows#1681]
When ds4 rumbles or lightbar lights up, it lasts longer than it should. Worked fine in 2.1.17(I think), updated to 2.1.22, now it doesn't work fine. Works fine with DInput only, only virtual controller is affected.

Lightbar issue doesn't happen with flashing lightbar, that one reacts instantly.

**To Reproduce**
1. Change colors to black (ie disable it)
2. Bind swipe up (or whatever) to change lightbar color to blue (or whichever)
3. Swipe up
4. Lift the finger off

 - Alternative:
 1. Open game with only virtual gamepad enabled
 2. Do something that starts the rumble (eg "Test Rumble" in DS4windows)
 3. Wait till rumble is supposed to end, or do something that disables it (eg "Stop Testing" in DS4windows)

**Expected behavior**
As long as I'm holding the touchbar after the swipe, it is blue. As soon as stop touching it, the lightbar turns off. What happens instead is that lightbar is still lit for like 3 seconds. 
Same with rumbling. It rumbles for like 3 extra seconds.

**Desktop (please complete the following information):**
 - Controller Make and Model: Sony DS4 v.2 (CUH-ZCT2E)
 - OS: Windows 10 Education 2004
 - DS4Windows Version: 2.1.22, portable version

**Additional context**

**Comment by mika-n** [comment]
Try using RBG 0,0,1 value and not the "all zero" RBG 0,0,0 value. The current version has few issues with all zero lightbar RBG color.

**Comment by stramner** [comment]
The workaround does fix the issue, though 0,0,1 is actually pretty different from 0,0,0. Anyways, the workaround I mentioned, with flashing light on swipe up seems alright as temporary solution in the context I use the lightbar. 

However, I'm more interested in the rumbling part of the problem. I wasn't 100% sure these 2 were connected, but I found out they both "linger" for exactly 4 extra seconds. As I mentioned, no problem with non-virtual DS with the rumbling, even if ds4windows is running. To add some info, I'm playing eg Celeste with virtual DS4, and when I die, the rumbling lasts 4 seconds longer than intended.

**Comment by mika-n** [comment]
try the latest version if it solves this issue

**Comment by trostboot** [comment]
I had the same issue (DS4 v1, vibration too long with lightbar off), and the latest version does not fix it. Workaround continues to work, of course.

**Comment by xuru-thor** [comment]
Also having the same issue. Waiting for a permanent fix.

**Comment by mika-n** [comment]
Strange. Here rumble and lightbar activity seems to work just fine (used the latest V2.1.23) even when the "normal" lightbar setting is set to RBG 0,0,0 value. When I set "swipe up" to change lightbar color or to rumble then lightbar went immediatly back to 0,0,0 and rumble stopped when I released a finger.

Maybe there is something else strange in the profile you have. Please zip the profile file and attach it here as an attachment.

**Comment by trostboot** [comment]
[Here's the one I normally use.](https://github.com/Ryochan7/DS4Windows/files/5743013/profile.zip)
No lightbar changes via touchpad or anything, but the rumble is still broken. Easy to test by setting autostop rumble to 1s in the profile setting and testing rumble there.

**Comment by mika-n** [comment]
The profile you sent works perfectly here. Rumble stops immediately after pressing "Stop" btn in DS4Windows or when a "real game" does something with the rumble or "test rumble" thing in Dolphin emulator.

Rumble work with "0 auto stop timer" (ie. keeps on rumbling until game sends 0-rumble value or I press "stop" rumble button in DS4Windows app). Also "1 auto stop timer" stops the rumble automagically after 1 sec if the game didn't do it.

This is very strange issue why it would not work there. At this point I don't have theories which could explain this (especially the Test Rumble functionality in DS4Windows app because when tested via it ViGem client driver issues should not have anything to do with this).

**Comment by stramner** [comment]
I can confirm that even on version 2.1.23 and creating entirely new profile with DS4 preset, changing only lightbar to 0,0,0 and nothing else, the issue persists. Always lasts exactly 4 extra seconds.

Probably irrelevant detail, but I renamed the DS4windows exe as workaround for it being blocked by some games.

PS: I want to add I wasn't originally aware the lightbar 0,0,1 recommendation was workaround for the problem as well, I thought it was only for the light issue

**Comment by LuismaSP89** [comment]
Same here, is also happening in the 2.1.23 version. Installed new Vigem driver 1.7 and makes no difference.

**Comment by xuru-thor** [comment]
Updated to version 2.2.1, rumble is even more broken now. The controller won't ever stop vibrating now until disconnected, unless auto stop is enabled. Also, changing the lightbar color to anything but 0,0,0 doesn't fix the issue anymore

**Comment by mika-n** [comment]
This is really really weird. The rumble works fine here with 2.2.1 even when the light is 0,0,0 (ie. the rumble is stopped immediatly when an app/game sends zero-rumble cmd). 

I tested this in various racing games, gamepad-tester.com web site and using Win10Store app called "Game Controller Tester" (it has a rumble test support when enabled via settings. Analog left and right triggers are used to drive those rumble motors, so it is easy way to test the strength and if the rumble stops immediately when a trigger is released). Works perfectly here using xbox360 and dualshock4 virtual output controller type (i have genuine DS4 v2 gamepad).

**Comment by LuismaSP89** [comment]
For me it works fine in the latest version "2.2.1" with the black light 0,0,0.

@xuru-thor Did you tried to install the latest vigem bus driver? Try to uninstall the 1.6 version and install the new version 1.7, then try it again. Also you can run a ccleaner to clean old data files.

**Comment by xuru-thor** [comment]
> For me it works fine in the latest version "2.2.1" with the black light 0,0,0.
> 
> @xuru-thor Did you tried to install the latest vigem bus driver? Try to uninstall the 1.6 version and install the new version 1.7, then try it again. Also you can run a ccleaner to clean old data files.

Thanks, that worked!

**Comment by trostboot** [comment]
Can confirm, rumble with lightbar completely off seems to be in working order again.
