### ISSUE TITLE
3.2.0 -> Previously set up special actions disappeared and new special actions get deleted after closing and opening the client again

### ISSUE THREAD

**Issue by andreycout** [Ryochan7/DS4Windows#2761]
**Bug description**
Upon updating to 3.2.0, all Special Actions got deleted/disappeared from the client. I tried setting them up again and, while they did save, after rebooting my PC they were all gone again. Upon further investigation, I realized that closing DS4Windows 3.2.0, it will wipe all Special Actions.

**To Reproduce**
1. Open DS4Windows
2. On the GUI, select a profile and click Edit
3. Go to the Special Actions Tab and click New
4. Set up a button combination, an action, name the Action and click save
5. After verifying that the special actions was correctly saved and works, close DS4Windows completly (right click the tray icon and select Exit)
6. Open DS4 Windows again

**Expected behavior**
The previously saved Special Action should appear on the Special Actions tab of the Profile Edit menu, but doesn't

**Desktop**
 - Controller Make and Model: Sony DualSense (white) CFI-ZCT1W
 - OS: Windows 11 latest stable build as of Jan. 06 2023 
 - DS4Windows Version 3.2.0

**Additional context**
The profiles tested were created prior to the current DS4Windows version.

**Comment by andreycout** [comment]
Further Testing: creating a new profile and setting up the special action there doesn't make a difference, bug still occurs as described above. As Special Actions seem to be independent from profiles, that's to be expected. Maybe it's a good time to migrate Special Actions to the profile XML (and maybe just offer a way to copy/paste them from one profile to another)? Just a suggetion...

**Comment by lalo876** [comment]
Giving a new special action to press a key on the keyboard results in a crash and shutdown of the application. This only happens when you give a key press command, other options such as macro recording/battery level check work fine.

**Comment by InterClaw** [comment]
Noticed something was off as well when trying to turn off the controller with the PS button and it turned off immediately (instead of after a delay like I have it set).

Downgrading to 3.1.12 worked fine. Profiles are intact.

**Comment by Ryochan7** [comment]
Several issues with serializing Special Actions. One critical problem is that the Special Action save routine accidentally writes to Profiles.xml instead of Actions.xml. Luckily the app will write the proper output to Profiles.xml upon closing so app settings are not lost. This is definitely a **high priority** issue that must be fixed and a new hotfix released ASAP.

Fortunately, I believe I got the issues fixed with commit f0d6c2d028258ee4e44a479e34c6935b709019f6. Going to attempt to get a new release out before I go to bed.

**Comment by Ryochan7** [comment]
Hotfix

https://github.com/Ryochan7/DS4Windows/releases/tag/v3.2.1

**Comment by lalo876** [comment]
I received your update @Ryochan7 but the problem persists. First, I installed the DS4Windows update, then the hotfix mentioned in the post below, but unfortunately it did not fix the problem for me. The program still crashes when I try to assign a special action to a keypress :-(

**Comment by lalo876** [comment]
Anyway, I found that going back to the previous version completely fixed my problem :-)

**Comment by DienH** [comment]
Same problem here with 3.2.1, my old actions doesn't appear, but are back when downgrading to 3.1.x.
Saving a new custom action in 3.2.1 from a new profile or an older one is crashing the program if I select a "Launch program" or "Press/toggle key" action. The other type of actions are saving well.
So I tried removing my all my "Program" actions saved in Actions.xml in %appdata%, and it's working, all my others actions are back.

**Comment by InterClaw** [comment]
For me everything is back to normal with 3.2.1. Thank you for the quick fix! :)

**Comment by andreycout** [comment]
Still have a problem with Special Actions on 3.2.1. After changing the buttons associated with a Special Action and clicking "save", the app crashes. Here's the the crash log:
[ds4windows_log_20230107.5.txt](https://github.com/Ryochan7/DS4Windows/files/10366717/ds4windows_log_20230107.5.txt)

**Comment by Mister-Curious** [comment]
I just updated to 3.2.8 and none of my actions built in 3.0.18 are being read. Is there somewhere new I need to migrate these or is there an incompatibility between these versions?
