### ISSUE TITLE
X360 controller no longer works on 1.5.5

### ISSUE THREAD

**Issue by Viscerous** [Ryochan7/DS4Windows#392]
I'm not sure what caused this entirely, I'm reporting this for a friend.
![wnuayb](https://user-images.githubusercontent.com/7198087/44043498-4f92c8f8-9f23-11e8-9ab9-ff1b830da3c1.png)

Everything seems to work fine but the X360 side of things don't. He's on Windows 7 however. I'm on Windows 10 and haven't noticed any issues. Rolling back to 1.5.4 fixed the issue entirely for him.

**Comment by jinkazama82it** [comment]
Probably the wrong version? 32bit and 64bit can seem the same but change more for an OS, in OS at 64bit the 32bit env is a virualization and not all work correctly under virtualized env, so make sure that your friend use the same bit version for it's current OS (obviusly a 64bit version don't work and can't be lauched on a 32bit OS).

**Comment by Viscerous** [comment]
@jinkazama82it Seems kind of unlikely this is the issue considering it was updated with the auto-updater.

**Comment by jinkazama82it** [comment]
mmmh, I never used the updater XD I made all update manually.
We can only wait for a reply from the developer.

**Comment by Ryochan7** [comment]
I don't see how this can be happening due to changes. Only minor changes to the UDP server and forms occurred with the most recent version. Nothing in the mapping system got changed.

**Comment by Ryochan7** [comment]
I just updated to version 1.5.5 on Windows 7 using the auto updater. DS4Windows worked fine for me for both USB and Bluetooth connections.

**Comment by Viscerous** [comment]
@Ryochan7 That's exactly what I was thinking so I walked him through a whole list of things, including restarting DS4, the PC, reinstalling SCP drivers, reinstalling X360 drivers, reconnecting wired or wireless. Only once I was out of ideas did I link him a previous version and the problem was solved. I'm quite confused as well.

**Comment by DoctorCandor** [comment]
I'm having the same issue on Windows 10 after applying the August cumulative update and updating to 1.5.5. The PS4 Controller shows up as a "Wireless Controller" rather than an Xbox 360 controller. Rolling back to 1.5.4 doesn't fix the issue.

**Comment by jinkazama82it** [comment]
@DoctorCandor sometime after an update the option value for hide the ds4 are unchecked and revert to an older version don't change the status of this option, you need to enable manually the option from settings tab.

**Comment by Viscerous** [comment]
@jinkazama82it That was the first thing I checked and was unchanged.

**Comment by DoctorCandor** [comment]
@jinkazama82it That option wasn't unchecked after the update, so that isn't my issue.

**Comment by DoctorCandor** [comment]
OK! Fixed my issue. I had to delete my profile settings (nuked the whole folder) under AppData to reset everything and have DS4Windows recreate the files. It works now!

**Comment by Ryochan7** [comment]
I'm going to just blame .NET for this one and move on. Thank you for reporting this issue though. Hopefully the issue corrected itself with version 1.5.6.
