### ISSUE TITLE
Windows 7 End of Life. RIP Windows 7

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/DS4Windows#922]
I only recently heard that Microsoft is officially ending support for Windows 7 on 2020/01/14. Due to that announcement, I will no longer keep Windows 7 SP1 as the minimum platform target for DS4Windows starting at the beginning of the year. Windows 8.1 will likely be the chosen minimum platform target. Although DS4Windows will likely still work in Windows 7 for the foreseeable future, no priority will be given to Windows 7 specific problems.

**Comment by Ryochan7** [comment]
Also, I should mention that the future WPF based DS4Windows is already confirmed to work in Windows 7. The upgrade to version 2.0 should not impact current Windows 7 users.

**Comment by Ryusennin** [comment]
A shame, because I don't myself permanently switching to my Win10 partition anytime soon. But as it is, DS4Windows has proven solid on Win7 for a long time now and I'll make sure to keep the latest functional version somewhere safe. Thanks for all your great work.

**Comment by TristanYoung** [comment]
I've been running DS4Windows on Windows 10 with no issues.  For me, Windows 10 is working very well for gaming.  Not saying it's for everyone, and a lot of my gaming buddies still run Windows 7, but it's mostly because they can't be bothered to upgrade.  It's still a free upgrade from Windows 7 Pro if you use the Media Creation Toolkit.  Been upgrading lots of machines to Windows 10 for free.

I like the interface better overall.  I run Windows 7 at work because the software we use requires about a $1000.00 service to fulfill the upgrade (stupid Pervasive database and DSN long name changes required).

**Comment by Ryusennin** [comment]
I'm not really looking for arguments to switch to Win10 (as I said, I have both systems). I personally find it ugly and half of the Win7 features are either hidden in submenus and nested clicks, only accessible through the search engine or the registry (like the fonts, of all things) or missing altogether. And let's not talk about legacy drivers -- for game controllers, MIDI synths, extension boards...

Then again, I'm ok with DS4W being frozen on Win7 as the current version works great and suits my needs.

**Comment by Ryochan7** [comment]
The day has arrived. RIP Windows 7.

![537568e](https://user-images.githubusercontent.com/581968/72409466-7be5ca80-372b-11ea-8c38-d8c863983946.jpg)

**Comment by Tiberiusmoon** [comment]
I still dunno why you wanna support the Win 8.1 with DS4 with the user base being >5% of the whole world.

**Comment by Ryusennin** [comment]
I will keep reporting if/when DS4Windows stops working on Win7.

**Comment by Ryochan7** [comment]
The app will likely work in Windows 7 for the extended future. I am using Microsoft's end of support decision as a way to reduce my own workload. Now I don't have to worry about having development tools installed on a Windows 7 VM just to test a few specific problems. Pull requests will be welcome in the case that Windows 7 specific fixes are needed in the code.

**Comment by Fierelier** [comment]
Windows 7 is no longer supported, does not mean that people should just go ahead and no longer care. I understand why you would do it, but you really shouldn't. Legacy support with devices suffers intensely in 8.1 and up, 7 still has a place.

I think Windows 7 should be an active priority, and that issues that may prop up with it should be fixed, even if 7 is a bit of an edge case now. Don't just pass off the old, **try** to give equal opportunities to everything for as long as it is possible. Not putting any care in this will just support software and hardware decay.

@Ryochan7, I am **not** asking you in particular to maintain compatibility to 7, I know this can be hard with today's crippled-for-7 hardware, and that you might not have much time. I'm asking you to make sure that Windows 7 is valued within this project by other contributors.

Please think about reverting this decision.

**Comment by Ryochan7** [comment]
If it weren't for the poor BT stack in Windows 7, I probably would not have been so quick to accept the death of Windows 7. Plus it does not help that ViGEmBus won't work on Windows 7 SP1 as is but later hot fixes need to be installed to be able to install and run the driver. Windows 7 support was already becoming a liability before Microsoft officially killed it.

I have changed my mind about not needing Windows 7 whatsoever though. Testing the old Jays2Kings build of DS4Windows is going to keep getting harder with Windows updates especially due to the outdated ScpVBus driver. I will likely still need a Windows 7 VM around in order to test out the old version 1.4.52 build.

**Comment by Fierelier** [comment]
Thank you for the detailed response, laying things down more and so on. Unfortunate to hear that the bt performance is sub-par. Thanks for taking it into consideration though, it is much appreciated!

**Comment by Ryochan7** [comment]
DS4Windows 2.0.12 is confirmed to work on Windows 7. Haven't broke Windows 7 compatibility yet.

**Comment by Ryusennin** [comment]
Reports of Win7's death have been greatly exaggerated. I still get daily updates for Windows Defender!

**Comment by Ryochan7** [comment]
This issue will stay relevant until DS4Windows no longer works in Windows 7. Luckily, DS4Windows 2.1.4 works in Windows 7 so compatibility has not been broken yet.

**Comment by Ryochan7** [comment]
The recent drama just goes to show that I cannot win. I am pretty much giving up providing any support and going back to the old stance of scratching my own itch.

**Comment by Fierelier** [comment]
All good, as long as the last Win7 compatible release stays available. Don't worry about it.

**Comment by Ryusennin** [comment]
Well, 2.1.9 is still compatible (at least via USB, haven't used BT for months).

**Comment by Ryochan7** [comment]
Since ViGEmBus 1.17.333.0 is only compatible with Windows 10, this issue is more important than ever before. If you are still running Windows 7, it would probably be best for you to make plans to eventually migrate to Windows 10.

**Comment by mirh** [comment]
It is my very superficial understanding that at least for the time being the client API should still remain the same.

**Comment by Fierelier** [comment]
@Ryochan7 Windows 10 is a pest. Points sorted by severity (most severe first):
- Each release is an utter mess (remember when they managed to delete user data, twice?) with [lackluster hardware testing](https://www.youtube.com/watch?v=S9kn8_oztsA). The frequency of these releases makes the OS inherently less stable (Windows 7 had 1 major update in the 10 years it was supported, Windows 10 had 10 as of now, 6 years after release) and it is impossible (without a fuckload of effort) to mod/fix it in a reliable, lasting manner.
- Bad defaults, stupid stuff forced, etc.. All the things other people already talked about. All unable to be fixed reliably due to the aforementioned rapid releases.
- The wasteful graphics composition (Aero) is forced, really bogging down slow GPUs and making borderless gaming's frame timing absolutely horrible.
- Non-WDDM video drivers are not able to be installed, making any GPU acceleration impossible on cards that only got updates until XP.

**If you really have to**, migrate to Linux instead, preferably a long term service distribution and don't bother trying to get proprietary shit like Photoshop to run. The effort spent there is way more valuable than trying to make this ever-(d)evolving OS enjoyable. I've been there.

Windows is dead.

**Comment by Ryochan7** [comment]
@Fierelier Been a Linux user since 2003. Windows 10 is a bloated mess and Microsoft has pretty much forced it upon all Windows users now. Too bad the Linux community is full of many bad actors and the community imploded on itself around 2018.  RIP Linux 1991-2018.

TempleOS is the real true Free Software Operating System. Praise Terry A. Davis

**Comment by Fierelier** [comment]
@Ryochan7 I personally thought Debian is **okay** for today's standards, if you're not using GNOME. It's still clunky in some spots but maybe it works nicely at some point. In terms of closed source OSes, with my software (and hardware) picks, even XP still does the job for me. 7 just has a little bit more of the fun stuff, without much extra bloat.

Either way, yes, praise Terry. He definitely had the right idea, everything is needlessly complicated nowadays.

Thank you.

**Comment by Ryochan7** [comment]
DS4Windows now officially will not work with Windows 7. I cannot deal with vague reports with people sometimes intentionally leaving out vital log information. I have to start enforcing things more strictly. Only ViGEmBus 1.17.333.0 will be supported starting with DS4Windows 3.0.2. DS4Windows will refuse to connect to ViGEmBus if an older version is detected.

I tried to accommodate.
